name: my-starter-workflow

on: 
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: action/checkout@v3
      -name: Run a multi line script
	 run: |
	   echo Add other actions to build
	   echo test & deploy
  call-workflow-in-local-repo:
    startegy:
      matrix:
        nodeversion [3,4,5,6]
	  uses: ./.github-workflow/reusable-workflow-1.yml
        node: {{matrix.nodeversion}}
